deployment:
  branch: main
  tasks:
   - source virtualenv/repositories/CRFC/3.12/bin/activate && cd /home/colches7/repositories/CRFC && pip install -r requirements.txt
    - mkdir -p /home/colches7/repositories/CRFC/tmp && touch /home/colches7/repositories/CRFC/tmp/restart.txt